moderation_craft:
  outputs:
    dev:
      type: duckdb
      path: './moderation_craft_dev.duckdb'
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: 'ap-northeast-1'
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
    
    prod:
      type: duckdb
      path: 's3://moderation-craft-data-800860245583/duckdb/prod.duckdb'
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: 'ap-northeast-1'
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
      
  target: dev